### ISSUE TITLE
Older torch versions `torch<2.0.0` are not supported by metatensor python modules

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/metatensor#501]
I am not sure if this is relevant but I tested it with python 3.8.

With torch version `1.13.1+cpu`
```python
================================================================================================
FAILED tests/atomistic/ase_calculator.py::test_torch_script_model - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED tests/atomistic/ase_calculator.py::test_exported_model - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED tests/atomistic/ase_calculator.py::test_serialize_ase - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED tests/operations/equal_metadata.py::test_operations_as_python - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
FAILED tests/operations/sort.py::test_operation_as_torch_script - RuntimeError: The following operation failed in the TorchScript interpreter.
FAILED tests/operations/sort.py::test_operation_as_python - IndexError: tensors used as indices must be long, byte or bool tensors
ERROR tests/learn/linear.py::test_linear_single_block_tensor - AttributeError: module 'torch' has no attribute 'set_default_device'
ERROR tests/learn/linear.py::test_linear_from_weight - AttributeError: module 'torch' has no attribute 'set_default_device'
ERROR tests/learn/linear.py::test_torchscript_linear - AttributeError: module 'torch' has no attribute 'set_default_device'
ERROR tests/learn/module_map.py::test_module_map_single_block_tensor[None] - AttributeError: module 'torch' has no attribute 'set_default_device'
ERROR tests/learn/module_map.py::test_module_map_single_block_tensor[out_properties1] - AttributeError: module 'torch' has no attribute 'set_default_device'
ERROR tests/learn/module_map.py::test_torchscript_module_map - AttributeError: module 'torch' has no attribute 'set_default_device'
======================================================================================= 6 failed, 158 passed, 6 errors in 15.62s ========================================================================================
torch-tests: exit 1 (15.97 seconds) /home/alexgo/code/metatensor/python/metatensor-torch> pytest --cov=/home/alexgo/code/metatensor/.tox/torch-tests/lib/python3.8/site-packages/metatensor --cov-append --cov-report= --import-mode=append -W error --tb=short pid=1298569
  torch-tests: FAIL code 1 (86.13=setup[1.23]+cmd[67.03,0.69,0.66,0.56,15.97] seconds)
  evaluation failed :( (86.19 seconds)
```

Tests work fine with torch version `2.0.0+cpu`.

Since metatensor-torch in principle supports Torch 1.11 according to the CMake file, version ``1.13.1+cpu` could be in principle supported. We probably need to check how easy it is to fix these and decide by that on a minimum version for the modules and then add these to the CI jobs.

**Comment by Luthaf** [comment]
So we do run CI with pytorch 1.11, but only for the C++ tests. I think we should keep supporting old-ish torch versions for a bit (maybe moving the minimal version to 1.13), and add the corresponding tests to CI!
